//
// Created by Joe Bekor on 19/10/2017.
//

#ifndef CPP_WASTE_RECYCLING_BEKOR_DUSTBINTESTS_H
#define CPP_WASTE_RECYCLING_BEKOR_DUSTBINTESTS_H


class DustbinTests {

};


#endif //CPP_WASTE_RECYCLING_BEKOR_DUSTBINTESTS_H
